static const char *petscmachineinfo = "\n"
"-----------------------------------------\n"
"Libraries compiled on 2025-04-23 11:29:01 on reproducible\n"
"Machine characteristics: Linux-6.11.0-1012-azure-x86_64-with-glibc2.34\n"
"Using PETSc directory: /home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol\n"
"Using PETSc arch: \n"
"-----------------------------------------\n";
static const char *petsccompilerinfo = "\n"
"Using C compiler: mpicc  -fPIC -Wall -Wwrite-strings -Wno-unknown-pragmas -Wno-lto-type-mismatch -fstack-protector -fvisibility=hidden -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda/petsc-3.23.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol=/usr/local/src/conda-prefix -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -fopenmp\n"
"Using Fortran compiler: mpifort  -fPIC -Wall -ffree-line-length-none -ffree-line-length-0 -Wno-lto-type-mismatch -Wno-unused-dummy-argument -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I${PREFIX}/include -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda/petsc-3.23.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol=/usr/local/src/conda-prefix -O3   -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -fopenmp\n"
"-----------------------------------------\n";
static const char *petsccompilerflagsinfo = "\n"
"Using include paths: -I/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/suitesparse -I/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/superlu-dist\n"
"-----------------------------------------\n";
static const char *petsclinkerinfo = "\n"
"Using C linker: mpicc\n"
"Using Fortran linker: mpifort\n"
"Using libraries: -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -lpetsc -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -L/home/conda/feedstock_root/build_artifacts/bld/rattler-build_petsc_1745407741/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib -lHYPRE -lspqr -lumfpack -lklu -lcholmod -lamd -lsuperlu_dist -lzmumps -lmumps_common -lpord -lpthread -lscalapack -lsuperlu -lfftw3_mpi -lfftw3 -llapack -lblas -lptesmumps -lptscotchparmetisv3 -lptscotch -lptscotcherr -lesmumps -lscotch -lscotcherr -lpthread -lparmetis -lmetis -lhdf5_hl -lhdf5 -lm -lyaml -lhwloc -lquadmath -ldl\n"
"-----------------------------------------\n";
