reference_solution:
  path: results/gs_20260323_125141_eps0.1_h0.00390625

coarse_solutions:
  path: results/gs_20260323_131257_eps0.1_h0.125

error: 
  quadrature_degree: 3
  degree: 1

output:
  directory: error_estimates