# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Sep 30 07:56:03 2024
# ------------------------------------------------

package:
  name: mpi
  version: 1.0.1
build:
  noarch: generic
  number: '0'
  string: mpich
requirements:
  build: []
  run: []
test:
  commands:
    - echo "I'm a metapackage"
about:
  home: https://github.com/conda-forge/mpi-feedstock
  license: BSD-3-Clause
  license_file: /home/conda/recipe_root/LICENSE.txt
  summary: Metapackage to select the MPI variant. Use conda's pinning mechanism in
    your environment to control which variant you want.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240930.5.1
  recipe-maintainers:
    - leofang
    - minrk
    - ocefpaf
  remote_url: https://github.com/conda-forge/mpi-feedstock
  sha: 5f8bf87c3f1c177499d8a0e07090fea37193af3d
