# This file created by conda-build 26.3.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 31 23:24:39 2026
# ------------------------------------------------

package:
  name: aiohttp
  version: 3.13.5
source:
  - url: https://files.pythonhosted.org/packages/77/9a/152096d4808df8e4268befa55fba462f440f14beab85e8ad9bf990516918/aiohttp-3.13.5.tar.gz
    sha256: 9d98cc980ecc96be6eb4c1994ce35d28d8b1f5e5208a23b421187d1209dbb7d1
  - url: https://github.com/aio-libs/aiohttp/archive/refs/tags/v3.13.5.tar.gz
    sha256: ce6c43ca5b029ecf88623b11970e8540f9db44d428e8e9b7ae1e3508d86c67ff
    folder: sources
build:
  number: '0'
  track_features: null
  script:
    - /home/conda/feedstock_root/build_artifacts/aiohttp_1774999547161/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
      -m pip install . -vv
  string: py311h55b9665_0
requirements:
  build:
    - _openmp_mutex 4.5 20_gnu
    - binutils_impl_linux-64 2.45.1 default_hfdba357_102
    - binutils_linux-64 2.45.1 default_h4852527_102
    - gcc_impl_linux-64 14.3.0 hbdf3cc3_18
    - gcc_linux-64 14.3.0 h298d278_22
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.45.1 default_hbd61a6d_102
    - libgcc 15.2.0 he0feb66_18
    - libgcc-devel_linux-64 14.3.0 hf649bbc_118
    - libgomp 15.2.0 he0feb66_18
    - libsanitizer 14.3.0 h8f1669f_18
    - libstdcxx 15.2.0 h934c35e_18
    - libstdcxx-devel_linux-64 14.3.0 h9f08a49_118
    - libzlib 1.3.2 h25fd6f3_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025c hc9c84f9_1
    - zstd 1.5.7 hb78ec9c_6
  host:
    - _openmp_mutex 4.5 20_gnu
    - bzip2 1.0.8 hda65f42_9
    - ca-certificates 2026.2.25 hbd8a1cb_0
    - cython 3.2.4 py311h0daaf2c_0
    - icu 78.3 h33c6efd_0
    - ld_impl_linux-64 2.45.1 default_hbd61a6d_102
    - libexpat 2.7.5 hecca717_0
    - libffi 3.5.2 h3435931_0
    - libgcc 15.2.0 he0feb66_18
    - libgcc-ng 15.2.0 h69a702a_18
    - libgomp 15.2.0 he0feb66_18
    - liblzma 5.8.2 hb03c661_0
    - libnsl 2.0.1 hb9d3cd8_1
    - libsqlite 3.52.0 hf4e2dac_0
    - libstdcxx 15.2.0 h934c35e_18
    - libuuid 2.41.3 h5347b49_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.2 h25fd6f3_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.6.1 h35e630c_1
    - packaging 26.0 pyhcf101f3_0
    - pip 26.0.1 pyh8b19718_0
    - pkg-config 0.29.2 h4bc722e_1009
    - pkgconfig 1.6.0 pyhd8ed1ab_0
    - python 3.11.15 hd63d673_0_cpython
    - python_abi 3.11 8_cp311
    - readline 8.3 h853b02a_0
    - setuptools 82.0.1 pyh332efcf_0
    - tk 8.6.13 noxft_h366c992_103
    - tzdata 2025c hc9c84f9_1
    - wheel 0.46.3 pyhd8ed1ab_0
    - zstd 1.5.7 hb78ec9c_6
  run:
    - __glibc >=2.17,<3.0.a0
    - aiohappyeyeballs >=2.5.0
    - aiosignal >=1.4.0
    - attrs >=17.3.0
    - frozenlist >=1.1.1
    - libgcc >=14
    - multidict >=4.5,<7.0
    - propcache >=0.2.0
    - python >=3.11,<3.12.0a0
    - python_abi 3.11.* *_cp311
    - yarl >=1.17.0,<2.0
test:
  requires:
    - brotli
    - brotlicffi
    - freezegun
    - gunicorn
    - pip
    - pkgconfig
    - proxy-py
    - pytest <8
    - pytest-codspeed
    - pytest-mock
    - python >=3.11,<3.12.0a0
    - python-blockbuster
    - python-isal
    - python-zlib-ng
    - re-assert
    - time-machine
    - trustme
    - uvloop
  source_files:
    - sources/README.rst
    - sources/tests
  imports:
    - aiohttp
  commands:
    - pip check
    - rm -rf sources/tests/autobahn
    - pytest sources/tests/ -k "not (_not_a_real_test or test_import_time or test_http_response_parser_strict_obs_line_folding
      or test_http_response_parser_bad_chunked_strict_c[pyloop] or test_http_response_parser_bad_chunked_strict_py[pyloop]
      or test_http_response_parser_strict_headers[c-parser-pyloop] or test_tcp_connector_raise_connector_ssl_error[pyloop]
      or test_heartbeat_no_pong[pyloop] or test_https_proxy_unsupported_tls_in_tls[pyloop-https]
      or (test_web_server and test_handler_cancellation) or (test_web_server and test_no_handler_cancellation)
      or test_run_app_preexisting_inet6_socket[pyloop] or test_invalid_idna[pyloop])"
about:
  home: https://github.com/aio-libs/aiohttp
  license: MIT AND Apache-2.0
  license_file:
    - LICENSE.txt
    - vendor/llhttp/LICENSE
  license_family: Apache
  summary: Async http client/server framework (asyncio)
  doc_url: http://aiohttp.readthedocs.io/
  dev_url: https://github.com/aio-libs/aiohttp
  doc_source_url: https://github.com/aio-libs/aiohttp/tree/master/docs
extra:
  recipe-maintainers:
    - ocefpaf
    - sodre
    - xhochy
    - xylar
  final: true
  copy_test_source_files: true
  flow_run_id: github_23824135480
  remote_url: https://github.com/conda-forge/aiohttp-feedstock
  sha: db6b0194df27a65e859feeb7f811181bdcc8601d
