# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: fenics-ffcx
  version: 0.9.0
source:
  sha256: afa517272a3d2249f513cb711c50b77cf8368dd0b8f5ea4b759142229204a448
  url: https://github.com/fenics/ffcx/archive/refs/tags/v0.9.0.tar.gz
build:
  entry_points:
    - ffcx = ffcx:__main__.main
  noarch: python
  number: 0
  string: pyh2e48890_0
requirements:
  host:
    - bzip2 1.0.8 h2466b09_7
    - ca-certificates 2024.8.30 h56e8100_0
    - libexpat 2.6.3 he0c23c2_0
    - libffi 3.4.2 h8ffe710_5
    - libmpdec 4.0.0 h2466b09_0
    - libsqlite 3.46.1 h2466b09_0
    - libzlib 1.3.1 h2466b09_2
    - openssl 3.3.2 h2466b09_0
    - pip 24.2 pyh145f28c_1
    - python 3.13.0 hf5aa216_100_cp313
    - python_abi 3.13 5_cp313
    - setuptools 75.1.0 pyhd8ed1ab_0
    - tk 8.6.13 h5226925_1
    - tzdata 2024b hc8b5060_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 h8a93ad2_22
    - vc14_runtime 14.40.33810 hcc2c482_22
    - vs2015_runtime 14.40.33810 h3bf8584_22
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h8d14728_0
  run:
    - cffi
    - fenics-basix 0.9.*
    - fenics-ufl 2024.2.*
    - numpy >=1.21
    - python >=3.9
    - setuptools
test:
  commands:
    - pytest -v test
  imports:
    - ffcx
  requires:
    - numba
    - pip
    - pygraphviz
    - pytest >=6
    - sympy
    - vs2022_win-64
  source_files:
    - test
about:
  description: 'FFCx is a new version of the FEniCS Form Compiler.

    It is being actively developed and is compatible with DOLFINx.


    FFCx is a compiler for finite element variational forms.

    From a high-level description of the form in the Unified Form Language (UFL),

    it generates efficient low-level C code that can be used to assemble the corresponding
    discrete operator (tensor).

    In particular, a bilinear form may be assembled into a matrix and a linear form
    may be assembled into a vector.

    FFCx may be used either from the command line (by invoking the ffcx command) or
    as a Python module (import ffcx).

    '
  dev_url: https://github.com/fenics/ffcx
  doc_url: https://docs.fenicsproject.org/ffcx/v0.9.0/
  home: https://fenicsproject.org
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: The FEniCSx Form Compiler
extra:
  copy_test_source_files: true
  feedstock-name: fenics-ffcx
  final: true
  flow_run_id: azure_20241009.5.1
  recipe-maintainers:
    - minrk
  remote_url: https://github.com/conda-forge/fenics-ffcx-feedstock
  sha: 46c0e069e3276687fe192e80be99c597331bb5ee
