# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: libglx
  version: 1.7.0
source:
  patches:
    - libglvnd_look_for_egl_icd_in_system_location.patch
  sha256: d0e1925a3c9aee0143b8c181ac31d5637c8faa081759c277b8e16c7075612c11
  url: https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v1.7.0/libglvnd-v1.7.0.tar.bz2
build:
  noarch: false
  noarch_python: false
  number: '2'
  string: ha4b6fd6_2
requirements:
  build:
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - sysroot_linux-64 2.17 h4a8ded7_18
    - tzdata 2024b hc8b5060_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.2.0 h77fa898_1
    - libglvnd 1.7.0 ha4b6fd6_2
    - libgomp 14.2.0 h77fa898_1
    - libxcb 1.17.0 h8a09558_0
    - pthread-stubs 0.4 hb9d3cd8_1002
    - xorg-libx11 1.8.10 h4f16b4b_0
    - xorg-libxau 1.0.11 hb9d3cd8_1
    - xorg-libxdmcp 1.1.5 hb9d3cd8_0
    - xorg-xorgproto 2024.1 hb9d3cd8_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libglvnd 1.7.0 ha4b6fd6_2
    - xorg-libx11 >=1.8.10,<2.0a0
test:
  commands:
    - test -f $PREFIX/lib/libGLX.so.0
about:
  home: https://gitlab.freedesktop.org/glvnd/libglvnd
  license: LicenseRef-libglvnd
  license_file: README.md
  summary: GL Vendor-Neutral Dispatch library
extra:
  copy_test_source_files: true
  feedstock-name: libglvnd
  final: true
  flow_run_id: azure_20241111.3.1
  recipe-maintainers:
    - ehfd
    - h-vetinari
    - hmaarrfk
    - isuruf
    - traversaro
  remote_url: https://github.com/conda-forge/libglvnd-feedstock
  sha: 62c376495618d8ac04c90fdae9c058b138a4706e
