mesh:
  domain:
    xmin: -2.0
    ymin: -2.0
    xmax: 2.0
    ymax: 2.0

  resolution:
    k: 3  # mesh refinement level (controls h = 2^{-k})

  element:
    degree: 1

physics:
  epsilon: 0.05      # scaling parameter (epsilon=1 corresponds to the unscaled problem)
  beta_unscaled: 1  # interaction strength (unscaled)
  omega_unscaled: 1.1  # rotation frequency (unscaled)

  potential_unscaled:  # parameters of the harmonic trapping potential (before scaling)
    gamma_x: 1.25
    gamma_y: 0.98
    trap_strength: 0.5

solver:
  quadrature_degree: 3
  tolerance: 1.0e-11

initial_condition:
  # mode options:
  # - superposition: analytical Gaussian + vortex superposition 
  # - projected_reference: load a fine solution and project it onto the current mesh
  # - loaded_state: load a precomputed solution already defined on the target mesh
  mode: loaded_state
  path: results/gs_20260327_131900_eps0.05_h0.125 #path: null     (if superposition)
