# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: libboost-devel
  version: 1.86.0
source:
  url: https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.bz2
  sha256: 1bed88e40401b2cb7a1f76d4bab499e352fa4d0c5f31c0dbae64e24d34d7513b
  patches:
    - patches/0001-Add-default-value-for-cxx-and-cxxflags-options-for-t.patch
    - patches/0002-Support-numpy-2.0.0b1.patch
    - patches/0003-Support-numpy-2.0.patch
build:
  run_exports:
    - libboost >=1.86.0,<1.87.0a0
  number: 4
  string: hfcd1e18_4
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - icu 75.1 he02047a_0
    - libboost 1.86.0 hed09d94_4
    - libboost-headers 1.86.0 ha770c72_4
    - libgcc 15.1.0 h767d61c_4
    - libgcc-ng 15.1.0 h69a702a_4
    - libgomp 15.1.0 h767d61c_4
    - liblzma 5.8.1 hb9d3cd8_2
    - libstdcxx 15.1.0 h8f9b012_4
    - libstdcxx-ng 15.1.0 h4852527_4
    - libzlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - libboost 1.86.0 hed09d94_4
    - libboost-headers 1.86.0 ha770c72_4
  run_constrained:
    - boost-cpp <0.0a0
test:
  files:
    - test
    - test_lib.bat
    - test_lib.sh
  requires:
    - gxx_linux-64 14.*
  commands:
    - test -d $PREFIX/lib/cmake/Boost-1.86.0
    - test -d $PREFIX/lib/cmake/boost_atomic-1.86.0
    - test -d $PREFIX/lib/cmake/boost_charconv-1.86.0
    - test -d $PREFIX/lib/cmake/boost_chrono-1.86.0
    - test -d $PREFIX/lib/cmake/boost_cobalt-1.86.0
    - test -d $PREFIX/lib/cmake/boost_container-1.86.0
    - test -d $PREFIX/lib/cmake/boost_context-1.86.0
    - test -d $PREFIX/lib/cmake/boost_contract-1.86.0
    - test -d $PREFIX/lib/cmake/boost_coroutine-1.86.0
    - test -d $PREFIX/lib/cmake/boost_date_time-1.86.0
    - test -d $PREFIX/lib/cmake/boost_filesystem-1.86.0
    - test -d $PREFIX/lib/cmake/boost_graph-1.86.0
    - test -d $PREFIX/lib/cmake/boost_iostreams-1.86.0
    - test -d $PREFIX/lib/cmake/boost_locale-1.86.0
    - test -d $PREFIX/lib/cmake/boost_log-1.86.0
    - test -d $PREFIX/lib/cmake/boost_log_setup-1.86.0
    - test -d $PREFIX/lib/cmake/boost_math_c99-1.86.0
    - test -d $PREFIX/lib/cmake/boost_math_c99f-1.86.0
    - test -d $PREFIX/lib/cmake/boost_math_tr1-1.86.0
    - test -d $PREFIX/lib/cmake/boost_math_tr1f-1.86.0
    - test -d $PREFIX/lib/cmake/boost_prg_exec_monitor-1.86.0
    - test -d $PREFIX/lib/cmake/boost_program_options-1.86.0
    - test -d $PREFIX/lib/cmake/boost_random-1.86.0
    - test -d $PREFIX/lib/cmake/boost_regex-1.86.0
    - test -d $PREFIX/lib/cmake/boost_serialization-1.86.0
    - test -d $PREFIX/lib/cmake/boost_system-1.86.0
    - test -d $PREFIX/lib/cmake/boost_thread-1.86.0
    - test -d $PREFIX/lib/cmake/boost_timer-1.86.0
    - test -d $PREFIX/lib/cmake/boost_type_erasure-1.86.0
    - test -d $PREFIX/lib/cmake/boost_unit_test_framework-1.86.0
    - test -d $PREFIX/lib/cmake/boost_wave-1.86.0
    - test -d $PREFIX/lib/cmake/boost_wserialization-1.86.0
    - test -d $PREFIX/lib/cmake/boost_math_c99l-1.86.0
    - test -d $PREFIX/lib/cmake/boost_math_tr1l-1.86.0
    - test -d $PREFIX/lib/cmake/boost_exception-1.86.0
    - test -d $PREFIX/lib/cmake/boost_test_exec_monitor-1.86.0
    - test ! -d $PREFIX/lib/cmake/boost_python-1.86.0
    - test ! -d $PREFIX/lib/cmake/boost_numpy-1.86.0
    - ./test_lib.sh
about:
  home: http://www.boost.org/
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: Free peer-reviewed portable C++ source libraries.
  dev_url: https://github.com/boostorg/boost
  doc_url: https://www.boost.org/doc/
extra:
  recipe-maintainers:
    - beckermr
    - ccordoba12
    - h-vetinari
    - isuruf
    - jakirkham
    - jschueller
    - matthiasdiener
    - msarahan
    - ocefpaf
    - scopatz
    - xhochy
  feedstock-name: boost
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250830.6.1
  remote_url: https://github.com/conda-forge/boost-feedstock
  sha: 7d4e85476da9e228f0eb6ecdcfc1beef656c6748
