# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jun 20 16:23:14 2025
# ------------------------------------------------

package:
  name: xcb-util
  version: 0.4.1
source:
  url: https://xcb.freedesktop.org/dist/xcb-util-0.4.1.tar.xz
  sha256: 5abe3bbbd8e54f0fa3ec945291b7e8fa8cfd3cccc43718f8758430f94126e512
build:
  number: '2'
  run_exports:
    - xcb-util >=0.4.1,<0.5.0a0
  string: h4f16b4b_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_5
    - binutils_linux-64 2.43 h4852527_5
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 h6f18a23_11
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_5
    - libgcc 15.1.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - libsanitizer 13.3.0 he8ea267_2
    - libstdcxx 15.1.0 h8f9b012_2
    - make 4.4.1 hb9d3cd8_2
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_2
    - libgomp 15.1.0 h767d61c_2
    - libxcb 1.17.0 h8a09558_0
    - pthread-stubs 0.4 hb9d3cd8_1002
    - xorg-libxau 1.0.12 hb9d3cd8_0
    - xorg-libxdmcp 1.1.5 hb9d3cd8_0
    - xorg-xproto 7.0.31 hb9d3cd8_1008
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libxcb >=1.17.0,<2.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libxcb-util.so
about:
  home: https://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Standard X key constants and conversion to/from keycodes
extra:
  recipe-maintainers:
    - hmaarrfk
    - scopatz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250620.2.1
  remote_url: https://github.com/conda-forge/xcb-util-feedstock
  sha: 33f236bd1e2eaf63ac142bbf9d0cc4e4fccef50e
