# This file created by conda-build 26.1.0
# ------------------------------------------------

package:
  name: freetype
  version: 2.14.3
source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.14.3.tar.gz
  sha256: e61b31ab26358b946e767ed7eb7f4bb2e507da1cfefeb7a8861ace7fd5c899a1
build:
  run_exports:
    - libfreetype >=2.14.3
    - libfreetype6 >=2.14.3
  number: 0
  string: ha770c72_0
requirements:
  host:
    - _openmp_mutex 4.5 20_gnu
    - libfreetype 2.14.3 ha770c72_0
    - libfreetype6 2.14.3 h73754d4_0
    - libgcc 15.2.0 he0feb66_18
    - libgomp 15.2.0 he0feb66_18
    - libpng 1.6.55 h421ea60_0
    - libzlib 1.3.2 h25fd6f3_2
  run:
    - libfreetype 2.14.3 ha770c72_0
    - libfreetype6 2.14.3 h73754d4_0
test:
  commands:
    - ${PREFIX}/bin/freetype-config --version
    - test -f ${PREFIX}/lib/libfreetype.so
    - test -f ${PREFIX}/lib/libfreetype.so.6
    - test -f ${PREFIX}/lib/libfreetype.so.6.20.6
    - test -f ${PREFIX}/include/freetype2/freetype/freetype.h
    - test -f ${PREFIX}/lib/pkgconfig/freetype2.pc
    - test -f ${PREFIX}/bin/freetype-config
    - test ! -f ${PREFIX}/lib/libfreetype.a
about:
  home: https://www.freetype.org/
  license: GPL-2.0-only OR FTL
  license_file:
    - docs/FTL.TXT
    - docs/GPLv2.TXT
  summary: A Free, High-Quality, and Portable Font Engine
  description: FreeType is designed to be small, efficient, highly customizable and
    portable while capable of producing high-quality output (glyph images) of most
    vector and bitmap font formats.
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  dev_url: http://git.savannah.gnu.org/cgit/freetype/
extra:
  recipe-maintainers:
    - carterbox
    - ccordoba12
    - msarahan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: github_23458678112
  remote_url: https://github.com/conda-forge/freetype-feedstock
  sha: 51c9b2727ccd6bc75eb7b5aa690502c23ecb49d3
