# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: binutils
  version: 2.45.1
source:
  - patches:
      - patches/0001-fallback-sysroot.diff
    sha256: 860daddec9085cb4011279136fc8ad29eb533e9446d7524af7f517dd18f00224
    url:
      - https://ftp.gnu.org/gnu/binutils/binutils-2.45.1.tar.bz2
      - https://mirrors.ocf.berkeley.edu/gnu/binutils/binutils-2.45.1.tar.bz2
build:
  detect_binary_files_with_prefix: false
  merge_build_host: false
  number: 102
  string: default_h4852527_102
requirements:
  host:
    - binutils_impl_linux-64
  run:
    - binutils_impl_linux-64 >=2.45.1,<2.45.2.0a0
test:
  commands:
    - $PREFIX/bin/addr2line --help
    - $PREFIX/bin/ar --help
    - $PREFIX/bin/as --help
    - $PREFIX/bin/c++filt --help
    - $PREFIX/bin/elfedit --help
    - $PREFIX/bin/gprof --help
    - $PREFIX/bin/ld --help
    - $PREFIX/bin/ld.bfd --help
    - $PREFIX/bin/nm --help
    - $PREFIX/bin/objcopy --help
    - $PREFIX/bin/objdump --help
    - $PREFIX/bin/ranlib --help
    - $PREFIX/bin/readelf --help
    - $PREFIX/bin/size --help
    - $PREFIX/bin/strings --help
    - $PREFIX/bin/strip --help
about:
  home: https://www.gnu.org/software/binutils/
  license: GPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LIB
    - COPYING3
    - COPYING3.LIB
  summary: 'A set of programming tools for creating and managing binary programs,
    object files,

    libraries, profile data, and assembly source code.

    '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20260322.1.1
  recipe-maintainers:
    - beckermr
    - frol
    - isuruf
    - jjhelmus
  remote_url: https://github.com/conda-forge/binutils-feedstock
  sha: 79fcfc43aaefbc044dd554e95c8c5ad3cbcff0a1
