# This file created by conda-build 24.5.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jun 20 01:58:16 2024
# ------------------------------------------------

package:
  name: xcb-util-renderutil
  version: 0.3.10
source:
  sha256: 3e15d4f0e22d8ddbfbb9f5d77db43eacd7a304029bf25a6166cc63caa96d04ba
  url: https://xcb.freedesktop.org/dist/xcb-util-renderutil-0.3.10.tar.xz
build:
  number: '0'
  run_exports:
    - xcb-util-renderutil >=0.3.10,<0.4.0a0
  string: hb711507_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_7
    - gcc_impl_linux-64 12.3.0 h58ffeeb_10
    - gcc_linux-64 12.3.0 h9528a6a_7
    - kernel-headers_linux-64 2.6.32 he073ed8_17
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc-devel_linux-64 12.3.0 h6b66f73_110
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libsanitizer 12.3.0 hb8811af_10
    - libstdcxx-ng 13.2.0 hc0a3c3a_10
    - make 4.3 hd18ef5c_1
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_17
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 13.2.0 h77fa898_10
    - libgomp 13.2.0 h77fa898_10
    - libxcb 1.16 hd590300_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - xorg-libxau 1.0.11 hd590300_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xorg-xproto 7.0.31 h7f98852_1007
  run:
    - libgcc-ng >=12
    - libxcb >=1.16,<1.17.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libxcb-render-util.so
about:
  home: https://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Provides additional extensions to the XCB library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240619.6.1
  recipe-maintainers:
    - erykoff
  remote_url: https://github.com/conda-forge/xcb-util-renderutil-feedstock
  sha: f5ea7665eff9e8652a23f02a5882c3204ba93d8b
