# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Sep 20 03:15:29 2024
# ------------------------------------------------

package:
  name: pthread-stubs
  version: '0.4'
source:
  fn: libpthread-stubs-0.4.tar.bz2
  sha256: e4d05911a3165d3b18321cc067fdd2f023f06436e391c6a28dff618a78d2e733
  url: https://www.x.org/releases/individual/xcb/libpthread-stubs-0.4.tar.bz2
build:
  detect_binary_files_with_prefix: true
  number: '1002'
  string: hb9d3cd8_1002
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_16
    - binutils_impl_linux-64 2.40 ha1999f0_7
    - binutils_linux-64 2.40 hb3c18ed_3
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_3
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - kernel-headers_linux-64 3.10.0 h4a8ded7_16
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libgcc 14.1.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.1.0 h69a702a_1
    - libgomp 14.1.0 h77fa898_1
    - libsanitizer 13.3.0 heb74ff8_1
    - libstdcxx 14.1.0 hc0a3c3a_1
    - make 4.4.1 hb9d3cd8_1
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h4a8ded7_16
    - tzdata 2024a h8827d51_1
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.1.0 h77fa898_1
    - libgomp 14.1.0 h77fa898_1
    - xorg-util-macros 1.19.3 hb9d3cd8_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
test:
  commands: null
about:
  home: https://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Stubs missing from libc for standard pthread functions
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240919.2.1
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
    - pkgw
  remote_url: https://github.com/conda-forge/pthread-stubs-feedstock
  sha: 4a2c874180a993b971c3038a8e60dc44ec1eac6e
