# This file created by conda-build 25.11.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Dec 24 04:05:20 2025
# ------------------------------------------------

package:
  name: zfp
  version: 1.0.1
source:
  url: https://github.com/LLNL/zfp/archive/1.0.1.tar.gz
  sha256: 4984db6a55bc919831966dd17ba5e47ca7ac58668f4fd278ebd98cd2200da66f
  patches:
    - fix_find_python_stuff.patch
    - fix_setup_py_brackets.patch
build:
  number: '5'
  script:
    - source ${RECIPE_DIR}/build_zfp.sh
  run_exports:
    - zfp >=1.0.1,<2.0a0
  string: h909a3a2_5
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.45 default_hfdba357_105
    - binutils_linux-64 2.45 default_h4852527_105
    - bzip2 1.0.8 hda65f42_8
    - c-ares 1.34.6 hb03c661_0
    - ca-certificates 2025.11.12 hbd8a1cb_0
    - cmake 4.2.1 hc85cc9f_0
    - gcc_impl_linux-64 14.3.0 he8b2097_16
    - gcc_linux-64 14.3.0 h298d278_17
    - gxx_impl_linux-64 14.3.0 h2185e75_16
    - gxx_linux-64 14.3.0 h310e576_17
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.45 default_hbd61a6d_105
    - libcurl 8.17.0 h4e3cde8_1
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.3 hecca717_0
    - libgcc 15.2.0 he0feb66_16
    - libgcc-devel_linux-64 14.3.0 hf649bbc_116
    - libgcc-ng 15.2.0 h69a702a_16
    - libgomp 15.2.0 he0feb66_16
    - liblzma 5.8.1 hb9d3cd8_2
    - libnghttp2 1.67.0 had1ee68_0
    - libsanitizer 14.3.0 h8f1669f_16
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.2.0 h934c35e_16
    - libstdcxx-devel_linux-64 14.3.0 h9f08a49_116
    - libstdcxx-ng 15.2.0 hdf11a46_16
    - libuv 1.51.0 hb03c661_1
    - libzlib 1.3.1 hb9d3cd8_2
    - make 4.4.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.6.0 h26f9b46_0
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025c h8577fbf_0
    - zstd 1.5.7 hb78ec9c_6
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.2.0 he0feb66_16
    - libgomp 15.2.0 he0feb66_16
    - libstdcxx 15.2.0 h934c35e_16
  run:
    - __glibc >=2.17,<3.0.a0
    - _openmp_mutex >=4.5
    - libgcc >=14
    - libstdcxx >=14
test:
  commands:
    - test -f $PREFIX/include/zfp.h
    - test -f ${PREFIX}/lib/cmake/zfp/zfp-config.cmake
    - test -f $PREFIX/lib/libzfp.so.1.0.1
    - test -f $PREFIX/lib/libzfp${SHLIB_EXT}
    - which zfp
about:
  home: https://zfp.llnl.gov
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Library for compressed numerical arrays that support high throughput read
    and write random access
  description: 'zfp is an open source C/C++ library for compressed numerical arrays

    that support high throughput read and write random access. zfp also

    supports streaming compression of integer and floating-point data,

    e.g., for applications that read and write large data sets to and

    from disk. zfp is primarily written in C and C++ but also includes

    Python and Fortran bindings.

    '
  doc_url: https://zfp.readthedocs.io/
  dev_url: https://github.com/LLNL/zfp
extra:
  feedstock-name: zfpy
  recipe-maintainers:
    - GarrettDMorrison
    - ToreAad
    - hmaarrfk
    - kmpaul
    - lindstro
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251223.7.1
  remote_url: https://github.com/conda-forge/zfpy-feedstock
  sha: 03cad87b4d4fb2d250ae7a2ba8105385a84ff76a
