# This file created by conda-build 25.11.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jan 24 02:27:51 2026
# ------------------------------------------------

package:
  name: libaec
  version: 1.1.5
source:
  url: https://gitlab.dkrz.de/k202009/libaec/-/archive/v1.1.5/libaec-v1.1.5.tar.gz
  sha256: 2e2a9a276783b8d7014cdb9127ffdb63e4c35dcd7b866d3383efda297f8cc040
build:
  number: '0'
  run_exports:
    - libaec >=1.1.5,<2.0a0
  string: h088129d_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.45 default_hfdba357_105
    - binutils_linux-64 2.45 default_h4852527_105
    - bzip2 1.0.8 hda65f42_8
    - c-ares 1.34.6 hb03c661_0
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - cmake 4.2.2 hc85cc9f_0
    - gcc_impl_linux-64 14.3.0 he8b2097_16
    - gcc_linux-64 14.3.0 h298d278_17
    - gxx_impl_linux-64 14.3.0 h2185e75_16
    - gxx_linux-64 14.3.0 h310e576_17
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.45 default_hbd61a6d_105
    - libcurl 8.18.0 h4e3cde8_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.3 hecca717_0
    - libgcc 15.2.0 he0feb66_16
    - libgcc-devel_linux-64 14.3.0 hf649bbc_116
    - libgcc-ng 15.2.0 h69a702a_16
    - libgomp 15.2.0 he0feb66_16
    - liblzma 5.8.2 hb03c661_0
    - libnghttp2 1.67.0 had1ee68_0
    - libsanitizer 14.3.0 h8f1669f_16
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.2.0 h934c35e_16
    - libstdcxx-devel_linux-64 14.3.0 h9f08a49_116
    - libstdcxx-ng 15.2.0 hdf11a46_16
    - libuv 1.51.0 hb03c661_1
    - libzlib 1.3.1 hb9d3cd8_2
    - make 4.4.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.6.0 h26f9b46_0
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025c hc9c84f9_1
    - zstd 1.5.7 hb78ec9c_6
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.2.0 he0feb66_16
    - libgomp 15.2.0 he0feb66_16
    - libstdcxx 15.2.0 h934c35e_16
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - libstdcxx >=14
test:
  commands:
    - test -f ${PREFIX}/lib/libaec${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libsz${SHLIB_EXT}
about:
  home: https://gitlab.dkrz.de/k202009/libaec
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Adaptive Entropy Coding library
  description: 'Libaec provides fast lossless compression of 1 up to 32 bit wide signed
    or unsigned integers (samples).

    The library achieves best results for low entropy data as often encountered in
    space imaging instrument

    data or numerical model output from weather or climate simulations. While floating
    point representations

    are not directly supported, they can also be efficiently coded by grouping exponents
    and mantissa.

    Libaec implements Golomb-Rice coding as defined in the Space Data System Standard
    documents 121.0-B-2

    and 120.0-G-2.

    '
  dev_url: https://gitlab.dkrz.de/k202009/libaec
extra:
  recipe-maintainers:
    - hmaarrfk
    - kmuehlbauer
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260123.2.1
  remote_url: https://github.com/conda-forge/libaec-feedstock
  sha: 7956da9b702b3cc5a37829b46808a5b0d26bd6c8
