# This file created by conda-build 24.9.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Nov  1 12:55:13 2024
# ------------------------------------------------

package:
  name: scalapack
  version: 2.2.0
source:
  fn: scalapack-2.2.0.tar.gz
  patches:
    - fortran_mangling_cross.patch
    - high_mem_32bits.patch
  sha256: 40b9406c20735a9a3009d863318cb8d3e496fb073d201c5463df810e01ab2a57
  url: http://www.netlib.org/scalapack/scalapack-2.2.0.tgz
build:
  number: '4'
  run_exports:
    - scalapack >=2.2.0,<2.3.0a0
  string: h7e29ba8_4
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_2
    - binutils_linux-64 2.43 h4852527_2
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.32.3 h4bc722e_0
    - ca-certificates 2024.8.30 hbcca054_0
    - cmake 3.30.5 hf9cb763_0
    - gcc_impl_linux-64 13.3.0 hfea6d02_1
    - gcc_linux-64 13.3.0 hc28eda2_5
    - gfortran_impl_linux-64 13.3.0 h10434e7_1
    - gfortran_linux-64 13.3.0 hb919d3a_5
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.43 h712a8e2_2
    - libcurl 8.10.1 hbbe4b11_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 hd590300_2
    - libexpat 2.6.3 h5888daf_0
    - libgcc 14.2.0 h77fa898_1
    - libgcc-devel_linux-64 13.3.0 h84ea5a7_101
    - libgcc-ng 14.2.0 h69a702a_1
    - libgfortran5 14.2.0 hd5240d6_1
    - libgomp 14.2.0 h77fa898_1
    - libnghttp2 1.64.0 h161d5f1_0
    - libsanitizer 13.3.0 heb74ff8_1
    - libssh2 1.11.0 h0841786_0
    - libstdcxx 14.2.0 hc0a3c3a_1
    - libstdcxx-ng 14.2.0 h4852527_1
    - libuv 1.49.2 hb9d3cd8_0
    - libzlib 1.3.1 hb9d3cd8_2
    - make 4.4.1 hb9d3cd8_2
    - ncurses 6.5 he02047a_1
    - openssl 3.3.2 hb9d3cd8_0
    - rhash 1.4.5 hb9d3cd8_0
    - sysroot_linux-64 2.17 h4a8ded7_18
    - tzdata 2024b hc8b5060_0
    - xz 5.2.6 h166bdaf_0
    - zstd 1.5.6 ha6fb4c9_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libblas 3.9.0 7_ha36c22a_netlib
    - libgcc 14.2.0 h77fa898_1
    - libgfortran 14.2.0 h69a702a_1
    - libgfortran5 14.2.0 hd5240d6_1
    - libgomp 14.2.0 h77fa898_1
    - liblapack 3.9.0 7_ha36c22a_netlib
    - libstdcxx 14.2.0 hc0a3c3a_1
    - mpi 1.0.1 mpich
    - mpich 4.2.3 h670b19f_100
  run:
    - __glibc >=2.17,<3.0.a0
    - libblas >=3.9.0,<4.0a0
    - libgcc >=13
    - libgfortran
    - libgfortran5 >=13.3.0
    - liblapack >=3.9.0,<4.0a0
    - mpich >=4.2.3,<5.0a0
test:
  commands:
    - test -f $PREFIX/lib/libscalapack.so
about:
  description: 'ScaLAPACK is a library of high-performance linear algebra routines
    for parallel distributed

    memory machines. ScaLAPACK solves dense and banded linear systems, least squares
    problems,

    eigenvalue problems, and singular value problems.

    '
  home: http://www.netlib.org/scalapack/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ScaLAPACK is a library of high-performance linear algebra routines for
    parallel distributed memory machines
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241101.6.1
  recipe-maintainers:
    - SylvainCorlay
    - dalcinl
    - davidbrochart
    - gdonval
    - minrk
    - traversaro
  remote_url: https://github.com/conda-forge/scalapack-feedstock
  sha: eb393b2d93b31f427c6e1d6666ee18f3536f391c
