# This file created by conda-build 24.9.0
# ------------------------------------------------

package:
  name: fenics-basix-nanobind-abi
  version: 0.2.1.13
source:
  sha256: 60e96b2393084729b261cb10370f0e44d12735ab3dbd1f15890dec23b9e85329
  url: https://github.com/fenics/basix/archive/refs/tags/v0.9.0.tar.gz
build:
  force_use_keys:
    - python
  number: 2
  run_exports:
    strong:
      - fenics-basix-nanobind-abi ==0.2.1.13
  string: h6c05e69_2
requirements:
  build: []
  run: []
  run_constrained:
    - gxx 13.*
    - gxx_impl_linux-64 13.*
    - nanobind 2.1.*
test:
  commands:
    - echo 'ok'
about:
  dev_url: https://github.com/fenics/basix
  doc_url: https://docs.fenicsproject.org/basix/main/
  home: https://fenicsproject.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Basix is a finite element definition and tabulation runtime library
extra:
  copy_test_source_files: true
  feedstock-name: fenics-basix
  final: true
  flow_run_id: azure_20241101.2.1
  recipe-maintainers:
    - minrk
  remote_url: https://github.com/conda-forge/fenics-basix-feedstock
  sha: 5541cdc48c3f5544876738203fe4a0fe566f35e0
