# This file created by conda-build 25.11.1
# ------------------------------------------------

package:
  name: libcurl
  version: 8.18.0
source:
  url: http://curl.haxx.se/download/curl-8.18.0.tar.bz2
  sha256: ffd671a3dad424fb68e113a5b9894c5d1b5e13a88c6bdf0d4af6645123b31faf
build:
  run_exports:
    - libcurl >=8.18.0,<9.0a0
  number: 0
  string: h4e3cde8_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.45 default_hfdba357_105
    - binutils_linux-64 2.45 default_h4852527_105
    - gcc_impl_linux-64 14.3.0 he8b2097_16
    - gcc_linux-64 14.3.0 h298d278_17
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.45 default_hbd61a6d_105
    - libgcc 15.2.0 he0feb66_16
    - libgcc-devel_linux-64 14.3.0 hf649bbc_116
    - libgomp 15.2.0 he0feb66_16
    - libsanitizer 14.3.0 h8f1669f_16
    - libstdcxx 15.2.0 h934c35e_16
    - libstdcxx-devel_linux-64 14.3.0 h9f08a49_116
    - libzlib 1.3.1 hb9d3cd8_2
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025c hc9c84f9_1
    - zstd 1.5.7 hb78ec9c_6
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - c-ares 1.34.6 hb03c661_0
    - ca-certificates 2026.1.4 hbd8a1cb_0
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libgcc 15.2.0 he0feb66_16
    - libgcc-ng 15.2.0 h69a702a_16
    - libgomp 15.2.0 he0feb66_16
    - libnghttp2 1.67.0 had1ee68_0
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.2.0 h934c35e_16
    - libstdcxx-ng 15.2.0 hdf11a46_16
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.4 h26f9b46_0
    - zlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb78ec9c_6
  run:
    - __glibc >=2.17,<3.0.a0
    - krb5 >=1.21.3,<1.22.0a0
    - libgcc >=14
    - libnghttp2 >=1.67.0,<2.0a0
    - libssh2 >=1.11.1,<2.0a0
    - libzlib >=1.3.1,<2.0a0
    - openssl >=3.5.4,<4.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/pkgconfig/libcurl.pc
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libcurl.a
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
about:
  home: http://curl.haxx.se/
  license: curl
  license_family: MIT
  license_file: COPYING
  summary: tool and library for transferring data with URL syntax
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  doc_url: https://curl.haxx.se/docs/
  dev_url: https://github.com/curl/curl
  doc_source_url: https://github.com/curl/curl/tree/master/docs
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260107.2.1
  remote_url: https://github.com/conda-forge/curl-feedstock
  sha: 3131e8ed693ad3669232c25959edecf942f45c28
