# This file created by conda-build 25.11.0
# ------------------------------------------------

package:
  name: _x86_64-microarch-level
  version: '3'
build:
  number: 3
  string: 3_x86_64_v3
  noarch: generic
requirements:
  run:
    - __archspec 1.* x86_64_v3
  build: []
about:
  home: https://github.com/conda-forge/microarch-level-feedstock
  summary: Meta package to build conda recipes with microarchitecture levels
  description: 'The meta-package _x86_64-microarch-level enforces the microarchitecture
    in the

    user system.


    Note that a user would need the archspec conda package installed

    in the base environment where conda/mamba is run from.

    Note also that this package is not intended to be directly interacted

    with by users.


    See x86_64-microarch-level for using this in conda recipes

    '
  license: BSD-3-Clause
  license_file: LICENSE.txt
extra:
  feedstock-name: microarch-level
  recipe-maintainers:
    - isuruf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20251124.4.1
  remote_url: https://github.com/conda-forge/microarch-level-feedstock
  sha: bc4ab257741a67cd89ebc618a179612612b6bd72
