[Paths]
Prefix = /opt/conda/envs/fem-gpe
Documentation = /opt/conda/envs/fem-gpe/share/doc/qt6
Headers = /opt/conda/envs/fem-gpe/include/qt6
Libraries = /opt/conda/envs/fem-gpe/lib
LibraryExecutables = /opt/conda/envs/fem-gpe/lib/qt6
Binaries = /opt/conda/envs/fem-gpe/lib/qt6/bin
Plugins = /opt/conda/envs/fem-gpe/lib/qt6/plugins
QmlImports = /opt/conda/envs/fem-gpe/lib/qt6/qml
ArchData = /opt/conda/envs/fem-gpe/lib/qt6
Data = /opt/conda/envs/fem-gpe/share/qt6
Translations = /opt/conda/envs/fem-gpe/share/qt6/translations
Examples = /opt/conda/envs/fem-gpe/share/doc/qt6/examples
Tests = /opt/conda/envs/fem-gpe/tests
