# This file created by conda-build 25.3.2
# ------------------------------------------------

package:
  name: mysql-libs
  version: 9.0.1
source:
  patches:
    - patches/0001-Make-installation-of-pdb-files-optional.patch
    - patches/0002-Fix-file-path-for-mysqlrouter.conf.sample-for-instal.patch
    - patches/0003-Allow-flags-other-than-macros-in-CPPFLAGS.patch
    - patches/0004-Add-include-header-for-std-string.patch
    - patches/0005-Remove-forceful-injection-of-debug-info.patch
    - patches/0006-Link-libgcc-libstdc-statically-for-codgen-binaries.patch
    - patches/0007-Add-dependency-on-comp_err-iff-that-target-exists.patch
    - patches/0008-Add-constructor-s-for-ut-Location.patch
    - patches/0009-Reduce-number-of-symbols-being-exported-from-mysqld..patch
    - patches/0010-Ensure-sql_main-uses-protobuf-shared-library-correct.patch
    - patches/0011-Include-missing-header-for-std-isdigit.patch
    - patches/0012-Print-number-of-lines-in-the-file-generated-by-creat.patch
    - patches/0013-Check-for-ARMv8-crc32-intrinsic-support-on-osx-arm64.patch
    - patches/0014-Revert-Bug-30981914-COMPILE-WITH-FASTER-TLS-MODEL.patch
    - patches/0015-Zlib-module-use-macro-instead-of-function.patch
    - patches/0016-Make-get_relative_path-binary-patching-friendly.patch
    - patches/0017-Revert-BUG-34849343-Aligned_atomic-not-working-as-in.patch
    - patches/0018-Make-libfido-checks-conditional.patch
    - patches/0019-Don-t-include-headers-from-Homebrew.patch
    - patches/0020-Use-config-mode-search-for-protobuf-first.patch
    - patches/0021-Simplify-protobuf-deps-using-cmake-alias.patch
    - patches/0022-Set-PROTOBUF_INCLUDE_DIR-only-if-not-set.patch
    - patches/0023-Allow-setting-WITH_SASL-none.patch
  sha256: 18fa65f1ea6aea71e418fe0548552d9a28de68e2b8bc3ba9536599eb459a6606
  url: https://cdn.mysql.com/Downloads/MySQL-9.0/mysql-9.0.1.tar.gz
build:
  number: 6
  script:
    - cmake -DCOMPONENT=SharedLibraries -P ${SRC_DIR}/build/cmake_install.cmake
  string: he0572af_6
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.34.4 hb9d3cd8_0
    - ca-certificates 2025.1.31 hbcca054_0
    - cmake 4.0.0 h74e3db0_0
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 hc28eda2_8
    - gxx_impl_linux-64 13.3.0 hae580e1_2
    - gxx_linux-64 13.3.0 h6834431_8
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libcurl 8.13.0 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.0 h5888daf_0
    - libgcc 14.2.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_0
    - libnghttp2 1.64.0 h161d5f1_0
    - libsanitizer 13.3.0 he8ea267_2
    - libssh2 1.11.1 hf672d98_0
    - libstdcxx 14.2.0 h8f9b012_2
    - libstdcxx-devel_linux-64 13.3.0 hc03c837_102
    - libstdcxx-ng 14.2.0 h4852527_2
    - libuv 1.50.0 hb9d3cd8_0
    - libzlib 1.3.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - ninja 1.12.1 h297d8ca_0
    - openssl 3.4.1 h7b32b05_0
    - rhash 1.4.5 hb9d3cd8_0
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - ca-certificates 2025.1.31 hbcca054_0
    - libgcc 14.2.0 h767d61c_2
    - libgomp 14.2.0 h767d61c_2
    - libstdcxx 14.2.0 h8f9b012_2
    - libzlib 1.3.1 hb9d3cd8_2
    - mysql-common 9.0.1 h266115a_6
    - openssl 3.4.1 h7b32b05_0
    - zlib 1.3.1 hb9d3cd8_2
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libstdcxx >=13
    - libzlib >=1.3.1,<2.0a0
    - mysql-common 9.0.1 h266115a_6
    - openssl >=3.4.1,<4.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libmysqlclient${SHLIB_EXT}
about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: Shared libraries for MySQL database client applications
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250408.3.1
  recipe-maintainers:
    - beckermr
    - nehaljwani
    - xhochy
  remote_url: https://github.com/conda-forge/mysql-feedstock
  sha: 629fbec667267f7d7d11be6fd004eb7a0b5b7bba
