# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jun 14 11:46:44 2025
# ------------------------------------------------

package:
  name: libpciaccess
  version: '0.18'
source:
  url: https://gitlab.freedesktop.org/xorg/lib/libpciaccess/-/archive/libpciaccess-0.18/libpciaccess-libpciaccess-0.18.tar.bz2
  sha256: c087f68008d91ebe0b5e5e77ca8568cf2c1ab35379f55cc098a5e87958808d90
build:
  number: '0'
  run_exports:
    - libpciaccess >=0.18,<0.19.0a0
  string: hb9d3cd8_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_5
    - binutils_linux-64 2.43 h4852527_5
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 h6f18a23_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_5
    - libexpat 2.7.0 h5888daf_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - liblzma 5.8.1 hb9d3cd8_2
    - libmpdec 4.0.0 hb9d3cd8_0
    - libsanitizer 13.3.0 he8ea267_2
    - libsqlite 3.50.1 hee588c1_0
    - libstdcxx 15.1.0 h8f9b012_2
    - libuuid 2.38.1 h0b41bf4_0
    - libzlib 1.3.1 hb9d3cd8_2
    - make 4.4.1 hb9d3cd8_2
    - meson 1.8.2 pyhe01879c_0
    - ncurses 6.5 h2d0b736_3
    - ninja 1.12.1 hff21bea_1
    - openssl 3.5.0 h7b32b05_1
    - pkg-config 0.29.2 h4bc722e_1009
    - python 3.13.5 hf636f53_101_cp313
    - python_abi 3.13 7_cp313
    - readline 8.2 h8c095d6_2
    - sysroot_linux-64 2.17 h0157908_18
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_2
    - libgomp 15.1.0 h767d61c_2
    - xorg-util-macros 1.20.2 hb9d3cd8_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
test:
  commands:
    - test -f $PREFIX/lib/libpciaccess.so
    - test -f $PREFIX/lib/libpciaccess.so.0
    - test -f $PREFIX/lib/pkgconfig/pciaccess.pc
    - test -f $PREFIX/include/pciaccess.h
about:
  home: https://gitlab.freedesktop.org/xorg/lib/libpciaccess
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Generic PCI access library
extra:
  recipe-maintainers:
    - hmaarrfk
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250614.5.1
  remote_url: https://github.com/conda-forge/libpciaccess-feedstock
  sha: f23ebea2a58d492d7e34d3e32c2dc364ccbdf08d
