# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Sep  7 02:25:15 2025
# ------------------------------------------------

package:
  name: libdrm
  version: 2.4.125
source:
  url: https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-2.4.125/drm-libdrm-2.4.125.tar.gz
  sha256: dd3e86a9fae99322d6430b28397f8e03ac4fb8deeed9a6e214bd5ced86db68c6
build:
  number: '1'
  run_exports:
    - libdrm >=2.4.125,<2.5.0a0
  string: hb03c661_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.34.5 hb9d3cd8_0
    - ca-certificates 2025.8.3 hbd8a1cb_0
    - cmake 4.1.1 hc85cc9f_0
    - gcc_impl_linux-64 14.3.0 hd9e9e21_5
    - gcc_linux-64 14.3.0 h1382650_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.3 hb9d3cd8_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.44 h1423503_1
    - libcurl 8.14.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.7.1 hecca717_0
    - libffi 3.4.6 h2dba641_1
    - libgcc 15.1.0 h767d61c_5
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_105
    - libgcc-ng 15.1.0 h69a702a_5
    - libgomp 15.1.0 h767d61c_5
    - liblzma 5.8.1 hb9d3cd8_2
    - libmpdec 4.0.0 hb9d3cd8_0
    - libnghttp2 1.67.0 had1ee68_0
    - libsanitizer 14.3.0 hd08acf3_5
    - libsqlite 3.50.4 h0c1763c_0
    - libssh2 1.11.1 hcf80075_0
    - libstdcxx 15.1.0 h8f9b012_5
    - libstdcxx-ng 15.1.0 h4852527_5
    - libuuid 2.38.1 h0b41bf4_0
    - libuv 1.51.0 hb03c661_1
    - libzlib 1.3.1 hb9d3cd8_2
    - meson 1.9.0 pyhcf101f3_0
    - ncurses 6.5 h2d0b736_3
    - ninja 1.13.1 h171cf75_0
    - openssl 3.5.2 h26f9b46_0
    - pkg-config 0.29.2 h4bc722e_1009
    - python 3.13.7 h2b335a9_100_cp313
    - python_abi 3.13 8_cp313
    - readline 8.2 h8c095d6_2
    - rhash 1.4.6 hb9d3cd8_1
    - sysroot_linux-64 2.17 h0157908_18
    - tk 8.6.13 noxft_hd72426e_102
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 15.1.0 h767d61c_5
    - libgomp 15.1.0 h767d61c_5
    - libpciaccess 0.18 hb9d3cd8_0
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - libpciaccess >=0.18,<0.19.0a0
test:
  commands:
    - test -f ${PREFIX}/include/xf86drm.h
    - test -f ${PREFIX}/include/xf86drmMode.h
    - test -f ${PREFIX}/include/libsync.h
    - test -d ${PREFIX}/include/libdrm
    - test -f ${PREFIX}/lib/libdrm.so
    - test -f ${PREFIX}/lib/libdrm.so.2
    - test -f ${PREFIX}/include/libdrm/intel_bufmgr.h
about:
  home: https://gitlab.freedesktop.org/mesa/drm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: userspace library for drm
  description: 'This  is libdrm,  a userspace  library for  accessing the  DRM, direct

    rendering  manager, on  Linux,  BSD and  other  operating systems that

    support the  ioctl interface.  The library  provides wrapper functions

    for the  ioctls to avoid  exposing the kernel interface  directly, and

    for chipsets with drm memory manager, support for tracking relocations

    and  buffers.   libdrm  is  a  low-level library,  typically  used  by

    graphics drivers  such as the Mesa  DRI drivers, the  X drivers, libva

    and  similar projects.  New  functionality in  the kernel  DRM drivers

    typically requires  a new  libdrm, but a  new libdrm will  always work

    with an older kernel.

    '
extra:
  recipe-maintainers:
    - hmaarrfk
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250906.3.1
  remote_url: https://github.com/conda-forge/libdrm-feedstock
  sha: a0d972b9179f7f0a7bf3e9ccb759e6906c5f7004
