# This file created by conda-build 26.3.0
# ------------------------------------------------

package:
  name: libfabric
  version: 2.5.1
source:
  url: https://github.com/ofiwg/libfabric/releases/download/v2.5.1/libfabric-2.5.1.tar.bz2
  sha256: ac34788a52b3e4a3a1ef712ec29bc4261c63dfbd9e5e4d6e202a0c3687be368d
build:
  number: '0'
  script_env:
    - LIBFABRIC_ABI=1.9
  noarch: false
  noarch_python: false
  python_version_independent: false
  string: ha770c72_0
requirements:
  run:
    - libfabric1 2.5.1 hf621623_0
  build: []
test:
  commands:
    - 'true'
about:
  home: http://libfabric.org/
  license: BSD-2-Clause OR GPL-2.0-only
  license_family: BSD
  license_file: COPYING
  summary: Libfabric is also known as Open Fabrics Interfaces (OFI).
extra:
  feedstock-name: libfabric
  recipe-maintainers:
    - j34ni
    - minrk
  final: true
  copy_test_source_files: true
  flow_run_id: github_24376541606
  remote_url: https://github.com/conda-forge/libfabric-feedstock
  sha: 17e60aa4b9c5c12eaa017ccf7dec569bc441413d
