# This file created by conda-build 25.1.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Mar 26 21:49:32 2025
# ------------------------------------------------

package:
  name: c-blosc2
  version: 2.17.1
source:
  sha256: 53c6ed1167683502f5db69d212106e782180548ca5495745eb580e796b7f7505
  url: https://github.com/Blosc/c-blosc2/archive/v2.17.1.tar.gz
build:
  number: '0'
  run_exports:
    - c-blosc2 >=2.17.1,<2.18.0a0
  string: h3122c55_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - bzip2 1.0.8 h4bc722e_7
    - c-ares 1.34.4 hb9d3cd8_0
    - ca-certificates 2025.1.31 hbcca054_0
    - cmake 3.31.6 h74e3db0_0
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 hc28eda2_8
    - gxx_impl_linux-64 13.3.0 hae580e1_2
    - gxx_linux-64 13.3.0 h6834431_8
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libcurl 8.12.1 h332b0f4_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libev 4.33 hd590300_2
    - libexpat 2.6.4 h5888daf_0
    - libgcc 14.2.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 14.2.0 h69a702a_2
    - libgomp 14.2.0 h767d61c_2
    - liblzma 5.6.4 hb9d3cd8_0
    - libnghttp2 1.64.0 h161d5f1_0
    - libsanitizer 13.3.0 he8ea267_2
    - libssh2 1.11.1 hf672d98_0
    - libstdcxx 14.2.0 h8f9b012_2
    - libstdcxx-devel_linux-64 13.3.0 hc03c837_102
    - libstdcxx-ng 14.2.0 h4852527_2
    - libuv 1.50.0 hb9d3cd8_0
    - libzlib 1.3.1 hb9d3cd8_2
    - make 4.4.1 hb9d3cd8_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.4.1 h7b32b05_0
    - rhash 1.4.5 hb9d3cd8_0
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
    - zstd 1.5.7 hb8e6e7a_2
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - libgcc 14.2.0 h767d61c_2
    - libgomp 14.2.0 h767d61c_2
    - libstdcxx 14.2.0 h8f9b012_2
    - libzlib 1.3.1 hb9d3cd8_2
    - lz4-c 1.10.0 h5888daf_1
    - zlib-ng 2.2.4 h7955e40_0
    - zstd 1.5.7 hb8e6e7a_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=13
    - libstdcxx >=13
    - lz4-c >=1.10.0,<1.11.0a0
    - zlib-ng >=2.2.4,<2.3.0a0
    - zstd >=1.5.7,<1.6.0a0
test:
  commands:
    - test -e $PREFIX/include/blosc2.h
    - test -e $PREFIX/include/blosc2/blosc2-export.h
    - test -e $PREFIX/lib/libblosc2${SHLIB_EXT}
    - test -e $PREFIX/lib/pkgconfig/blosc2.pc
about:
  description: 'Next generation of C-Blosc library bringing in a new container (schunk)
    that can optionally be persisted (frame).  Also, more filters, codecs and other
    bells and whistles like pre-filter support have been added.  The API tries to
    be as compatible as possible with the original C-Blosc.

    '
  home: https://github.com/Blosc/c-blosc2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A simple, compressed, fast and persistent data store library for C
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250326.2.1
  recipe-maintainers:
    - FrancescAlted
    - hmaarrfk
    - zklaus
  remote_url: https://github.com/conda-forge/c-blosc2-feedstock
  sha: e7fa64834ae53df68516c7e612a1e0616ce902e6
