# This file created by conda-build 25.4.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri May 23 14:18:18 2025
# ------------------------------------------------

package:
  name: openldap
  version: 2.6.10
source:
  sha256: c065f04aad42737aebd60b2fe4939704ac844266bc0aeaa1609f0cad987be516
  url: https://openldap.org/software/download/OpenLDAP/openldap-release/openldap-2.6.10.tgz
build:
  number: '0'
  run_exports:
    - openldap >=2.6.10,<2.7.0a0
  string: he970967_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.43 h4bf12b8_4
    - binutils_linux-64 2.43 h4852527_4
    - gcc_impl_linux-64 13.3.0 h1e990d8_2
    - gcc_linux-64 13.3.0 hc28eda2_10
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - groff 1.23.0 pl5321h5888daf_1
    - gxx_impl_linux-64 13.3.0 hae580e1_2
    - gxx_linux-64 13.3.0 h6834431_10
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.43 h712a8e2_4
    - libgcc 15.1.0 h767d61c_2
    - libgcc-devel_linux-64 13.3.0 hc03c837_102
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - libsanitizer 13.3.0 he8ea267_2
    - libstdcxx 15.1.0 h8f9b012_2
    - libstdcxx-devel_linux-64 13.3.0 hc03c837_102
    - libxcrypt 4.4.36 hd590300_1
    - make 4.4.1 hb9d3cd8_2
    - perl 5.32.1 7_hd590300_perl5
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - ca-certificates 2025.4.26 hbd8a1cb_0
    - cyrus-sasl 2.1.27 h54b06d7_7
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.3 h659f571_0
    - libedit 3.1.20250104 pl5321h7949ede_0
    - libgcc 15.1.0 h767d61c_2
    - libgcc-ng 15.1.0 h69a702a_2
    - libgomp 15.1.0 h767d61c_2
    - libntlm 1.8 hb9d3cd8_0
    - libstdcxx 15.1.0 h8f9b012_2
    - libstdcxx-ng 15.1.0 h4852527_2
    - ncurses 6.5 h2d0b736_3
    - openssl 3.5.0 h7b32b05_1
  run:
    - __glibc >=2.17,<3.0.a0
    - cyrus-sasl >=2.1.27,<3.0a0
    - krb5 >=1.21.3,<1.22.0a0
    - libgcc >=13
    - libstdcxx >=13
    - openssl >=3.5.0,<4.0a0
test:
  commands:
    - test $PREFIX/include/ldap.h
about:
  dev_url: https://www.openldap.org/software/repo.html
  doc_url: https://www.openldap.org/doc/
  home: https://www.openldap.org
  license: OLDAP-2.8
  license_family: BSD
  license_file: LICENSE
  summary: 'OpenLDAP Software is an open source implementation of the Lightweight
    Directory Access Protocol.

    '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20250523.2.1
  recipe-maintainers:
    - bollwyvl
    - mariusvniekerk
  remote_url: https://github.com/conda-forge/openldap-feedstock
  sha: ee50f5f3fb9db706d8883794e0493d553fa71c63
