# This file created by conda-build 25.5.0
# ------------------------------------------------

package:
  name: c-compiler
  version: 1.10.0
build:
  number: '0'
  noarch: false
  noarch_python: false
  python_version_independent: false
  string: h2b85faf_0
requirements:
  run:
    - binutils
    - gcc
    - gcc_linux-64 13.*
  build: []
test:
  commands:
    - $CC --help
    - cc --help > /dev/null
    - cpp --help > /dev/null
    - gcc --help > /dev/null
    - gcc-ar --help > /dev/null
    - gcc-nm --help > /dev/null
    - gcc-ranlib --help > /dev/null
    - gcov --help > /dev/null
    - gcov-dump --help > /dev/null
    - gcov-tool --help > /dev/null
about:
  home: https://conda-forge.org
  license: BSD-3-Clause
  summary: A metapackage to obtain a C compiler
  description: 'This package is a generic way to obtain the C compiler for your system

    that conda-forge used to compile its ecosystem.  This compiler is,

    therefore, guaranteed to be ABI compatible with the conda packages

    you have installed.


    This compiler metapackage is a convenience ONLY for users.

    Do NOT use this package as a build or host dependency in other

    recipes.  Use the Jinja template function compiler(''c'') instead.

    '
extra:
  recipe-maintainers:
    - chrisburr
    - duncanmmacleod
    - isuruf
    - scopatz
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250628.1.1
  remote_url: https://github.com/conda-forge/compilers-feedstock
  sha: ce3248e2b5bc60e0c7f9fdaa3920c72dc05008c0
