# This file created by conda-build 25.5.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jul 16 13:42:23 2025
# ------------------------------------------------

package:
  name: libhwloc
  version: 2.11.2
source:
  url: https://www.open-mpi.org/software/hwloc/v2.11/downloads/hwloc-2.11.2.tar.gz
  sha256: 866ac8ef07b350a6a2ba0c6826c37d78e8994dcbcd443bdd2b436350de19d540
  patches:
    - patches/0001-utils-lstopo-don-t-build-lstopo-win-with-MSVC.patch
build:
  number: '1002'
  string: default_h3d81e11_1002
  run_exports:
    - libhwloc >=2.11.2,<2.11.3.0a0
  track_features: null
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.72 pl5321hbb4ee43_1
    - automake 1.17 pl5321ha770c72_0
    - binutils_impl_linux-64 2.44 h4bf12b8_1
    - binutils_linux-64 2.44 h4852527_1
    - gcc_impl_linux-64 14.3.0 hd9e9e21_3
    - gcc_linux-64 14.3.0 h1382650_11
    - gxx_impl_linux-64 14.3.0 he663afc_3
    - gxx_linux-64 14.3.0 ha7acb78_11
    - kernel-headers_linux-64 3.10.0 he073ed8_18
    - ld_impl_linux-64 2.44 h1423503_1
    - libgcc 15.1.0 h767d61c_3
    - libgcc-devel_linux-64 14.3.0 h85bb3a7_103
    - libgcc-ng 15.1.0 h69a702a_3
    - libgomp 15.1.0 h767d61c_3
    - libltdl 2.4.3a h5888daf_0
    - libsanitizer 14.3.0 hd08acf3_3
    - libstdcxx 15.1.0 h8f9b012_3
    - libstdcxx-devel_linux-64 14.3.0 h85bb3a7_103
    - libtool 2.5.4 h5888daf_0
    - libxcrypt 4.4.36 hd590300_1
    - m4 1.4.20 hb9d3cd8_0
    - make 4.4.1 hb9d3cd8_2
    - perl 5.32.1 7_hd590300_perl5
    - pkg-config 0.29.2 h4bc722e_1009
    - sysroot_linux-64 2.17 h0157908_18
    - tzdata 2025b h78e105d_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - icu 75.1 he02047a_0
    - libgcc 15.1.0 h767d61c_3
    - libgcc-ng 15.1.0 h69a702a_3
    - libgomp 15.1.0 h767d61c_3
    - libiconv 1.18 h4ce23a2_1
    - liblzma 5.8.1 hb9d3cd8_2
    - libstdcxx 15.1.0 h8f9b012_3
    - libstdcxx-ng 15.1.0 h4852527_3
    - libxml2 2.13.8 h4bc477f_0
    - libzlib 1.3.1 hb9d3cd8_2
  run:
    - __glibc >=2.17,<3.0.a0
    - libgcc >=14
    - libstdcxx >=14
    - libxml2 >=2.13.8,<2.14.0a0
test:
  commands:
    - hwloc-ls
    - test -f ${PREFIX}/lib/libhwloc${SHLIB_EXT}
about:
  home: https://www.open-mpi.org/projects/hwloc/
  dev_url: https://github.com/open-mpi/hwloc
  license: BSD-3-Clause
  license_file: COPYING
  summary: Portable Hardware Locality (hwloc)
  description: 'This feedstock builds the hwloc library in the `libhwloc` conda package.
    Different variants of the package are built:

    * `default` in the build string: Without CUDA or ROCM support, installed by default.
    Install specifically this version with `conda install libhwloc=*=*default*`.

    * `cuda` in the build string: With CUDA support. Install specifically this version
    with  `conda install libhwloc=*=*cuda*`

    * `rocm` in the build string: With ROCM support. Install specifically this version
    with  `conda install libhwloc=*=*rocm*`

    '
extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - jan-janssen
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20250716.2.1
  remote_url: https://github.com/conda-forge/libhwloc-feedstock
  sha: 66616f188abef79f6922b2ff9867404ecca9c55d
