# This file created by conda-build 26.1.0
# ------------------------------------------------

package:
  name: libfreetype
  version: 2.14.3
source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.14.3.tar.gz
  sha256: e61b31ab26358b946e767ed7eb7f4bb2e507da1cfefeb7a8861ace7fd5c899a1
build:
  number: '0'
  noarch: false
  noarch_python: false
  python_version_independent: false
  string: ha770c72_0
requirements:
  run:
    - libfreetype6 >=2.14.3
  build: []
about:
  license: GPL-2.0-only OR FTL
  summary: The libfreetype runtime library.
  description: This is a runtime meta-package only. Developers should install freetype
    to build with libfreetype.
extra:
  recipe-maintainers:
    - carterbox
    - ccordoba12
    - msarahan
    - ocefpaf
  final: true
  copy_test_source_files: true
  flow_run_id: github_23458678112
  remote_url: https://github.com/conda-forge/freetype-feedstock
  sha: 51c9b2727ccd6bc75eb7b5aa690502c23ecb49d3
